<?php

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function ln_tint_connector_styles_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__tint_component' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 * Preprocesses variables for the page template.
 *
 * @param array $variables
 *   An associative array containing variables to pass to the theme template.
 */
function ln_tint_connector_styles_preprocess_page(&$variables) {
  $setParams = \Drupal::service('ln_tint_connector_styles.set_tint_params');
  $result = $setParams->preprocessPage($variables);
  if($result) {
    $variables = $result;
  }
 }


/**
 * Implements hook_theme_suggestions_HOOK_alter() for paragraph templates.
 */
function ln_tint_connector_styles_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  $paragraph = $variables['elements']['#paragraph'];
  if ($paragraph->bundle() == 'dsu_tint') {
      if ($paragraph?->get('field_styles_connector')?->value['activate']) {
        $suggestions[] = 'paragraph__tint_component';
      }
  }
}


